/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiplataforma;

/**
 *
 * @author user
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuAlumno = new javax.swing.JMenu();
        jMIAgreAlum = new javax.swing.JMenuItem();
        jMenuMateria = new javax.swing.JMenu();
        jMIAgreMat = new javax.swing.JMenuItem();
        jMenuInscripcion = new javax.swing.JMenu();
        jMIAgreInscri = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        jMenuAlumno.setText("Alumno");
        jMenuAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlumnoActionPerformed(evt);
            }
        });

        jMIAgreAlum.setText("Agregar Alumno");
        jMIAgreAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgreAlumActionPerformed(evt);
            }
        });
        jMenuAlumno.add(jMIAgreAlum);

        jMenuBar2.add(jMenuAlumno);

        jMenuMateria.setText("Materia");

        jMIAgreMat.setText("Agregar Materia");
        jMIAgreMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgreMatActionPerformed(evt);
            }
        });
        jMenuMateria.add(jMIAgreMat);

        jMenuBar2.add(jMenuMateria);

        jMenuInscripcion.setText("Inscripcion");

        jMIAgreInscri.setText("Inscribirse");
        jMIAgreInscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgreInscriActionPerformed(evt);
            }
        });
        jMenuInscripcion.add(jMIAgreInscri);

        jMenuBar2.add(jMenuInscripcion);

        jMenuSalir.setText("Salir");
        jMenuBar2.add(jMenuSalir);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlumnoActionPerformed

    }//GEN-LAST:event_jMenuAlumnoActionPerformed

    private void jMIAgreAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgreAlumActionPerformed
        AgregarAlumno alumno = new AgregarAlumno();
        escritorio.add(alumno);
        alumno.show();
    }//GEN-LAST:event_jMIAgreAlumActionPerformed

    private void jMIAgreInscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgreInscriActionPerformed
        AgregarInscripcion inscripcion = new AgregarInscripcion();
        escritorio.add(inscripcion);
        inscripcion.show();
    }//GEN-LAST:event_jMIAgreInscriActionPerformed

    private void jMIAgreMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgreMatActionPerformed
        AgregarMateria materia = new AgregarMateria();
        escritorio.add(materia);
        materia.show();
    }//GEN-LAST:event_jMIAgreMatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMIAgreAlum;
    private javax.swing.JMenuItem jMIAgreInscri;
    private javax.swing.JMenuItem jMIAgreMat;
    private javax.swing.JMenu jMenuAlumno;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuInscripcion;
    private javax.swing.JMenu jMenuMateria;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
